export const pageData = [
  {
    id: 'gadvadakrng886a',
    type: 'title',
    module_name: 'title_1_1',
    state: 's_state1',
    variant: 's_state4',
    label_state: ['s_state6', 's_state7'],
    title: 'メインページタイトル',
    label: '重要なお知らせ',
    image_url: '/assets/img/hero_image.jpg',
    image_alt: 'メインビジュアル画像',
    category: 'news',
    tags: ['important', 'featured'],
    nested_parts: [
      {
        id: 'nested_text_001',
        type: 'text',
        module_name: 'text_1_2',
        size: 's_large',
        heading: '詳細情報セクション',
        content:
          '<p>このセクションでは<strong>重要な情報</strong>をお伝えします。</p><p>お客様のニーズに合わせて、最適なソリューションを提供いたします。</p><p>リッチテキスト編集により、<em>書式設定</em>や<u>装飾</u>、<a href="#">リンク</a>なども設定できます。</p>',
        topics: ['technology', 'design'],
        source: 'オフィシャル発表',
      },
      {
        id: 'nested_title_001',
        type: 'title',
        module_name: 'title_1_2',
        style: 's_secondary',
        title: 'サブセクションタイトル',
        description: '詳細な説明文がここに入ります。',
        subtitle: 'サブタイトル補足',
        priority: 'high',
        nested_parts: [
          {
            id: 'deep_nested_text_001',
            type: 'text',
            module_name: 'text_1_1',
            state: 's_state1',
            content:
              '<p>これは3階層目のネストテキストです。</p><p><strong>深い階層</strong>でもTiptap編集が可能です。</p>',
            author: '開発チーム',
            features: ['highlight', 'important'],
            nested_parts: [
              {
                id: 'very_deep_nested_text_001',
                type: 'text',
                module_name: 'text_1_2',
                size: 's_small',
                heading: '4階層目の見出し',
                content:
                  '<p>これは<em>4階層目</em>のネストテキストです！</p><p>無限階層システムが正常に動作しています。</p>',
              },
              {
                id: 'very_deep_nested_button_001',
                type: 'button',
                module_name: 'button_1_1',
                style: 's_secondary',
                size: 's_small',
                type_button_type: 'button',
                text: '4階層目ボタン',
                tooltip: '4階層目のボタン説明',
                effects: ['hover', 'focus'],
                icons: ['edit'],
              },
            ],
          },
          {
            id: 'deep_nested_button_001',
            type: 'button',
            module_name: 'button_1_1',
            style: 's_danger',
            size: 's_small',
            type_button_type: 'button',
            text: '深層ボタン',
          },
        ],
      },
      {
        id: 'aasdvadaqrng886a',
        type: 'button',
        module_name: 'button_1_1',
        style: 's_primary',
        size: 's_large',
        type_button_type: 'button',
        text: '詳細を見る',
        tooltip: 'クリックして詳細ページに移動',
        effects: ['hover', 'active'],
        icons: ['plus', 'edit'],
      },
    ],
    cards: [
      {
        id: 'card_001',
        card_state: 's_state2',
        card_title: 'サービス1',
        card_desc: '高品質なサービスを提供します',
        nested_parts: [
          {
            id: 'nested_text_002_1',
            type: 'text',
            module_name: 'text_1_1',
            content: 'サービス1の詳細説明テキストです。',
            title: 'サービス1詳細',
          },
        ],
      },
      {
        id: 'card_002',
        card_state: 's_state1',
        card_title: 'サービス2',
        card_desc: 'お客様のニーズに合わせたソリューション',
        nested_parts: [
          {
            id: 'nested_text_002_2',
            type: 'text',
            module_name: 'text_1_1',
            content:
              'サービス2の詳細説明テキストです。お客様のニーズに合わせてカスタマイズされたソリューションを提供します。',
            title: 'サービス2詳細',
          },
        ],
      },
      {
        id: 'card_003',
        card_state: 's_state2',
        card_title: 'サービス3',
        card_desc: '24時間サポート体制',
        nested_parts: [
          {
            id: 'nested_text_002_3',
            type: 'text',
            module_name: 'text_1_1',
            content:
              'サービス3の詳細説明テキストです。24時間体制でサポートを提供し、お客様の安心をお約束します。',
            title: 'サービス3詳細',
          },
        ],
      },
    ],
  },
  {
    id: 'gaddadakrng886a',
    type: 'text',
    module_name: 'text_1_1',
    state: 's_state2',
    content:
      '<p>追加のテキストコンテンツです。</p><p>複数の段落を含むことができます。</p><p><strong>Tiptapエディター</strong>により、<em>書式設定</em>、<u>下線</u>、<mark>ハイライト</mark>、<a href="https://example.com">リンク</a>などの機能を使用できます。</p>',
  },
  {
    id: 'button_section_001',
    type: 'button',
    module_name: 'button_1_1',
    style: 's_secondary',
    size: 's_medium',
    type_button_type: 'submit',
    text: '送信する',
    tooltip: 'フォームを送信します',
    effects: ['focus', 'active'],
    icons: ['save', 'plus'],
  },
]
